### ISSUE TITLE
After installing with pip, how to use Opedia?

### ISSUE THREAD

**Issue by jcmcnch** [mdashkezari/opedia#2]
Hi Mohammad,

Following the instructions on the website for installing conda environments, I was able to install opedia via pip after running the following commands (on Ubuntu 18.04):

`sudo apt-get install unixodbc-dev`
`pip install opedia --ignore-installed`

It seems to be successfully installed, if I type `pip freeze`, then I see opedia==0.1.52. But I don't know how to access the program itself. If I type in opedia on bash, I see this:

`jesse@ubuntu-delltron:/~ $ opedia
opedia: command not found`

Am I missing something here?

Thanks,

Jesse

**Comment by norlandrhagen** [comment]
Hi Jesse,
We don't have a GUI for linux yet (only mac and windows at the moment); working on the web app.

Below is a link to a short jupyter notebook showing a few functionalities.
[notebook](https://opedia.io/notebooks)

opedia CLI and a full documentation are in preparation ...

**Comment by invertdna** [comment]
Sort of the same question here, but I'm on a mac (OS 10.14).  I seem to have everything installed correctly, but can't figure out how to launch anything at all...I can find neither a GUI nor a command-line executable for opedia.

**Comment by mdashkezari** [comment]
did you run the jupyter notebook example?

**Comment by invertdna** [comment]
Aha -- ok, will do.

**Comment by mdashkezari** [comment]
we are working on the project doc. It's not ready yet; but Raphael is very aggressively working on it.
Hopefully all of the installation tips (GUI/and non-GUI) and tutorials will be there. 
The current temporary url is below (there is a typo in the url :p )

https://simmons-ocean-atlas-documentation.readthedocs.io/en/latest/index.html

**Comment by norlandrhagen** [comment]
ok, I believe you don't have the db connection set up yet.
let's, first focus on MacOS, we will do the Linux installation, later.

First, please make sure that you have anaconda ([download link, ](https://www.anaconda.com/download/#macos) preferably python 3*). 
Anaconda python should be in path after installation. You can check it by:
$ which python

(if you already have homebrew, ignore the first command below)
```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew install unixodbc
$ brew install freetds --with-unixodbc

$ conda install shapely
$ conda install fiona
$ conda install -c conda-forge geopandas
$ pip uninstall opedia      (if you already have an older opedia [avoid --upgrade for now, please] )
$ pip install opedia
```

Then:
```
$ cd ~/Desktop
$ python
>> from opedia import getCatalog
```

If everything ok, you will see a directory "data" on your desktop; inside there is a single csv file containing a list of all variables in opedia.

At this point all example notebooks at  @[https://opedia.io/notebooks](https://opedia.io/notebooks) should run.


there are some instructions for linux [here](https://simmons-ocean-atlas-documentation.readthedocs.io/en/latest/getting_started/getting_started.html#linux). 
Please note that the documentation is temporary and will is quickly evolving.

We will add the GUI installation instructions soon. 

Thanks
Mohammad.
