### ISSUE TITLE
UnboundLocalError: local variable 'conn' referenced before assignment

### ISSUE THREAD

**Issue by jcmcnch** [mdashkezari/opedia#3]
Hi folks,

When running the example notebooks (using jupyter-notebook), I get a weird error:

`---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-1-205d6e655fed> in <module>()
     15 
     16 
---> 17 df = CRS.getCruiseTrack(DB_Cruise, source, cruise)
     18 df = CRS.resample(df, resampTau)
     19 loadedTrack = CRS.plotAlongTrack(tables, variables, cruise, resampTau, df, spatialTolerance, depth1, depth2, fname, exportDataFlag, marker='-', msize=30, clr='darkturquoise')

/home/jesse/miniconda3/lib/python2.7/site-packages/opedia/plotCruise.pyc in getCruiseTrack(DB_Cruise, source, cruise)
     46     if DB_Cruise:
     47         query = CruiseQuery(source, cruise)
---> 48         df = db.dbFetch(query)
     49     else:
     50         df = pd.read_csv(source)

/home/jesse/miniconda3/lib/python2.7/site-packages/opedia/db.pyc in dbFetch(query)
     21 
     22 def dbFetch(query):
---> 23     conn = dbConnect()
     24     df = sql.read_sql(query, conn)
     25     conn.close()

/home/jesse/miniconda3/lib/python2.7/site-packages/opedia/db.pyc in dbConnect(usr, psw, ip, port, db)
     17     except Exception as e:
     18         print('Database connection error. Error message: '+str(e))
---> 19     return conn
     20 
     21 

UnboundLocalError: local variable 'conn' referenced before assignment`

When I go into my python installation, I can load the opedia module just fine. Any thoughts as to what this error means?

Thanks,

Jesse

**Comment by mdashkezari** [comment]
Can you first confirm if you can successfully run all examples of the "SimpleExamples.ipynb" notebook, please? thanks

**Comment by jcmcnch** [comment]
No, unfortunately it doesn't work. First cell causes the same error:

![screenshot from 2018-10-30 11-14-53](https://user-images.githubusercontent.com/5956604/47740562-4c859380-dc35-11e8-91e1-27db7babbaa9.png)

**Comment by mdashkezari** [comment]
ok, I believe you don't have the db connection set up yet.
let's, first focus on MacOS, we will do the Linux installation, later.

First, please make sure that you have anaconda ([download link, ](https://www.anaconda.com/download/#macos) preferably python 3*). 
Anaconda python should be in path after installation. You can check it by:
$ which python

(if you already have homebrew, ignore the first command below)
```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew install unixodbc
$ brew install freetds --with-unixodbc

$ conda install shapely
$ conda install fiona
$ conda install -c conda-forge geopandas
$ pip uninstall opedia      (if you already have an older opedia [avoid --upgrade for now, please] )
$ pip install opedia
```

Then:
```
$ cd ~/Desktop
$ python
>> from opedia import getCatalog
```

If everything ok, you will see a directory "data" on your desktop; inside there is a single csv file containing a list of all variables in opedia.

At this point all example notebooks at  @[https://opedia.io/notebooks](https://opedia.io/notebooks) should run.


there are some instructions for linux [here](https://simmons-ocean-atlas-documentation.readthedocs.io/en/latest/getting_started/getting_started.html#linux). 
Please note that the documentation is temporary and will is quickly evolving.


I'll share the GUI installation instructions soon.

**Comment by jcmcnch** [comment]
Turns out this was an issue with the library for the SQL database not being in the right place.

Here's what I did to solve it:

```
(opedia-env) jesse@ubuntu-delltron:/~ $ locate libtdsodbc.so
/home/jesse/miniconda3/envs/opedia-env/lib/libtdsodbc.so
/home/jesse/miniconda3/envs/opedia-env/lib/libtdsodbc.so.0
/home/jesse/miniconda3/envs/opedia-env/lib/libtdsodbc.so.0.0.0
/home/jesse/miniconda3/pkgs/freetds-1.00.89-h831ec23_0/lib/libtdsodbc.so
/home/jesse/miniconda3/pkgs/freetds-1.00.89-h831ec23_0/lib/libtdsodbc.so.0
/home/jesse/miniconda3/pkgs/freetds-1.00.89-h831ec23_0/lib/libtdsodbc.so.0.0.0
/home/jesse/miniconda3/pkgs/freetds-1.00.97-h1ba5d50_0/lib/libtdsodbc.so
/home/jesse/miniconda3/pkgs/freetds-1.00.97-h1ba5d50_0/lib/libtdsodbc.so.0
/home/jesse/miniconda3/pkgs/freetds-1.00.97-h1ba5d50_0/lib/libtdsodbc.so.0.0.0
(opedia-env) jesse@ubuntu-delltron:/~ $ sudo cp /home/jesse/miniconda3/envs/opedia-env/lib/libtdsodbc.so /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
```

**Comment by jcmcnch** [comment]
Also, if you have installed conda in a specific environment like I have, you will have to install this package as well:

`conda install nb_conda`

Then once you start a jupyter-notebook, then change the kernel to your local environment's kernel.

**Comment by hkanju34** [comment]
hello Team,
i had the same issue and succeed to resolve, it was the connection issue with the PG database.
